### ISSUE TITLE
Plot_boundaries not working

### ISSUE THREAD

**Issue by Dennis-Dekker** [Dennis-Dekker/Machine_learning#3]
Look into plotting the boundaries of classification. Seems function is not working.  See [Script](https://github.com/Dennis-Dekker/Machine_learning/blob/master/Classification.py)

**Comment by DavideBrex** [comment]
Yes I commented it because i could not figure out how to plot the boundaries. If someone finds a solution thanks

**Comment by Dennis-Dekker** [comment]
I see you tried to plot the boundaries today, did it work?

**Comment by DavideBrex** [comment]
Hi Dennis, yes i'm still trying to solve it, but nothing. I moved forward to the roc plot, but also there i found some problems (due to the fact that ROC plot is usually made for 2 class).

**Comment by DavideBrex** [comment]
fixed! use only numpy
